version: '3.3'

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  ufeed:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:@db:5432/ufeed
      CARGO_HOME: /usr/src/app/tmp/cargo
    command: cargo run
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
